Feat: Explain Sponsored
Relewise/relewise-demos-shop-vue pull request #30
Opened 2024-10-07 13:42 UTC by SWH-Relewise

Jeg tager gerne i mod forbedringer til hvad der skal stå! 💗

![image](https://github.com/user-attachments/assets/2cc585fa-1457-4529-b10d-74c6c041d010)
https://trello.com/c/khcqWf5K/7854-demo-shop-add-a-small-hint-why-am-i-seeing-this-to-the-sponsored-label-in-retail-media-product-listings

2024-10-07 14:48 UTC, mzanoni commented
Synes ikke det helt matcher opgavebeskrivelsen:
![image](https://github.com/user-attachments/assets/ce04b376-a712-4c90-a80f-ecaf7e4a49fc)

2024-10-08 05:59 UTC, SWH-Relewise commented
@mzanoni Orgh jeg har kun set hvad der har stået på kortet! 😟

2024-10-08 11:21 UTC, SWH-Relewise commented
![image](https://github.com/user-attachments/assets/6e8a96b1-a042-4f67-a33a-a395133c7987)

2024-10-08 11:22 UTC, SWH-Relewise commented
@mzanoni 
Jeg har snupptet tool tips fra my relewise. 😊

2024-10-08 11:33 UTC, mzanoni requested changes
Skide godt @SWH-Relewise :)

2024-10-08 11:33 UTC, mzanoni commented on src/components/ProductTile.vue
> +                <Popover v-if="isPromotion" placement="bottom-start">
Jeg ville nok have puttet denne ind i den blå promotion boks for bedre at vise at de hører sammen :)

2024-10-08 11:33 UTC, mzanoni commented on src/components/ProductTile.vue
> +                                <div class="font-semibold px-2 text-14 bg-gray-100 py-2">
Jeg tror ikke `text-14` findes i din `tailwind.config.js`

2024-10-08 11:33 UTC, mzanoni commented on src/components/ProductTile.vue
> +                                <div class="p-2 text-13">
Jeg tror ikke `text-13` findes i din `tailwind.config.js`

2024-10-08 12:47 UTC, SWH-Relewise commented
![image](https://github.com/user-attachments/assets/abd5af62-353f-4d4b-bf0d-99609f916a5b)

2024-10-08 13:01 UTC, merged